# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ""
author: ""
copyright: "2022"
logo: images/reaktoro-for-python-and-cpp.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/reaktoro/reaktoro-jupyter-book  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: images/reaktoro-logo.svg
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true

# Sphinx configurations
sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  config:
    pygments_style: material
    bibtex_reference_style: author_year

parse:
  myst_substitutions:
      _0: <sub>0</sub>
      _1: <sub>1</sub>
      _2: <sub>2</sub>
      _3: <sub>3</sub>
      _4: <sub>4</sub>
      _5: <sub>5</sub>
      _6: <sub>6</sub>
      _7: <sub>7</sub>
      _8: <sub>8</sub>
      _9: <sub>9</sub>
      bibliography: |
        ```{bibliography}
        :style: unsrt
        :filter: docname in docnames
        ```
      Database:                "[`Database`](https://reaktoro.org/api/classReaktoro_1_1Database.html)"
      PhreeqcDatabase:         "[`PhreeqcDatabase`](https://reaktoro.org/api/classReaktoro_1_1PhreeqcDatabase.html)"
      ThermoFunDatabase:       "[`ThermoFunDatabase`](https://reaktoro.org/api/classReaktoro_1_1ThermoFunDatabase.html)"
      SupcrtDatabase:          "[`SupcrtDatabase`](https://reaktoro.org/api/classReaktoro_1_1SupcrtDatabase.html)"
      NasaDatabase:            "[`NasaDatabase`](https://reaktoro.org/api/classReaktoro_1_1NasaDatabase.html)"

      Element:                 "[`Element`](https://reaktoro.org/api/classReaktoro_1_1Element.html)"
      Species:                 "[`Species`](https://reaktoro.org/api/classReaktoro_1_1Species.html)"
      Phase:                   "[`Phase`](https://reaktoro.org/api/classReaktoro_1_1Phase.html)"
      Reaction:                "[`Reaction`](https://reaktoro.org/api/classReaktoro_1_1Reaction.html)"

      AqueousPhase:            "[`AqueousPhase`](https://reaktoro.org/api/classReaktoro_1_1AqueousPhase.html)"
      CondensedPhase:          "[`CondensedPhase`](https://reaktoro.org/api/classReaktoro_1_1CondensedPhase.html)"
      CondensedPhases:         "[`CondensedPhases`](https://reaktoro.org/api/classReaktoro_1_1CondensedPhases.html)"
      GaseousPhase:            "[`GaseousPhase`](https://reaktoro.org/api/classReaktoro_1_1GaseousPhase.html)"
      IonExchangePhase:        "[`MineralPhases`](https://reaktoro.org/api/classReaktoro_1_1MineralPhases.html)"
      LiquidPhase:             "[`LiquidPhase`](https://reaktoro.org/api/classReaktoro_1_1LiquidPhase.html)"
      MineralPhase:            "[`MineralPhase`](https://reaktoro.org/api/classReaktoro_1_1MineralPhase.html)"
      MineralPhases:           "[`MineralPhases`](https://reaktoro.org/api/classReaktoro_1_1MineralPhases.html)"
      SolidPhase:              "[`SolidPhase`](https://reaktoro.org/api/classReaktoro_1_1SolidPhase.html)"
      Phases:                  "[`Phases`](https://reaktoro.org/api/classReaktoro_1_1Phases.html)"

      ChemicalSystem:          "[`ChemicalSystem`](https://reaktoro.org/api/classReaktoro_1_1ChemicalSystem.html)"
      ChemicalState:           "[`ChemicalState`](https://reaktoro.org/api/classReaktoro_1_1ChemicalState.html)"
      ChemicalProps:           "[`ChemicalProps`](https://reaktoro.org/api/classReaktoro_1_1ChemicalProps.html)"
      ThermoProps:             "[`ThermoProps`](https://reaktoro.org/api/classReaktoro_1_1ThermoProps.html)"
      AqueousProps:            "[`AqueousProps`](https://reaktoro.org/api/classReaktoro_1_1AqueousProps.html)"

      StandardThermoProps:     "[`StandardThermoProps`](https://reaktoro.org/api/structReaktoro_1_1StandardThermoProps.html)"
      ReactionThermoProps:     "[`ReactionThermoProps`](https://reaktoro.org/api/structReaktoro_1_1ReactionThermoProps.html)"

      EquilibriumSpecs:        "[`EquilibriumSpecs`](https://reaktoro.org/api/classReaktoro_1_1EquilibriumSpecs.html)"
      EquilibriumRestrictions: "[`EquilibriumRestrictions`](https://reaktoro.org/api/classReaktoro_1_1EquilibriumRestrictions.html)"
      EquilibriumConditions:   "[`EquilibriumConditions`](https://reaktoro.org/api/classReaktoro_1_1EquilibriumConditions.html)"
      EquilibriumSolver:       "[`EquilibriumSolver`](https://reaktoro.org/api/classReaktoro_1_1EquilibriumSolver.html)"
      EquilibriumSensitivity:  "[`EquilibriumSensitivity`](https://reaktoro.org/api/classReaktoro_1_1EquilibriumSensitivity.html)"
      EquilibriumPredictor:    "[`EquilibriumPredictor`](https://reaktoro.org/api/classReaktoro_1_1EquilibriumPredictor.html)"
      EquilibriumOptions:      "[`EquilibriumOptions`](https://reaktoro.org/api/structReaktoro_1_1EquilibriumOptions.html)"
      EquilibriumResult:       "[`EquilibriumResult`](https://reaktoro.org/api/structReaktoro_1_1EquilibriumResult.html)"

      ElementList:             "[`ElementList`](https://reaktoro.org/api/classReaktoro_1_1ElementList.html)"
      PhaseList:               "[`PhaseList`](https://reaktoro.org/api/classReaktoro_1_1PhaseList.html)"
      SpeciesList:             "[`SpeciesList`](https://reaktoro.org/api/classReaktoro_1_1SpeciesList.html)"

      FormationReaction:       "[`FormationReaction`](https://reaktoro.org/api/classReaktoro_1_1FormationReaction.html)"
      ChemicalFormula:         "[`ChemicalFormula`](https://reaktoro.org/api/classReaktoro_1_1ChemicalFormula.html)"
      Elements:                "[`Elements`](https://reaktoro.org/api/classReaktoro_1_1Elements.html)"
      CriticalProps:           "[`CriticalProps`](https://reaktoro.org/api/classReaktoro_1_1CriticalProps.html)"
      DissociationReactions:   "[`DissociationReactions`](https://reaktoro.org/api/classReaktoro_1_1DissociationReactions.html)"
      ReactionEquation:        "[`ReactionEquation`](https://reaktoro.org/api/classReaktoro_1_1ReactionEquation.html)"
      ElementalComposition:    "[`ElementalComposition`](https://reaktoro.org/api/classReaktoro_1_1ElementalComposition.html)"

      WaterElectroProps:       "[`WaterElectroProps`](https://reaktoro.org/api/structReaktoro_1_1WaterElectroProps.html)"
      WaterThermoProps:        "[`WaterThermoProps`](https://reaktoro.org/api/structReaktoro_1_1WaterThermoProps.html)"
      WaterHelmholtzProps:     "[`WaterHelmholtzProps`](https://reaktoro.org/api/structReaktoro_1_1WaterHelmholtzProps.html)"
