name: reaktoro-jupyter-book

channels:
  - conda-forge

dependencies:
  - bokeh=2
  - importlib_metadata
  - jsonschema-with-format-nongpl
  - jupyter-book
  - matplotlib-base
  - numba
  - numpy
  - pandas
  - pip
  - python=3.10
  - reaktoro
  - reaktplot
  - sphinx-book-theme
  - sphinx-inline-tabs
  - webcolors
