name: reaktoro-jupyter-book

channels:
  - conda-forge

dependencies:
  - reaktoro
  - pip
  - pip:
    - numpy
    - numba
    - matplotlib
    - bokeh
    - pandas
    - jupyter-book
    - sphinx-inline-tabs
    - importlib_metadata
