name: reaktoro-jupyter-book

channels:
  - conda-forge

dependencies:
  - reaktoro
  - reaktplot
  - pip
  - pip:
    - bokeh
    - importlib_metadata
    - jupyter-book
    - matplotlib
    - numba
    - numpy
    - pandas
    - sphinx-inline-tabs
